# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(verbose_name='\u5ea6\u6570')),
                ('image', models.ImageField(upload_to='elec', verbose_name='\u56fe\u7247')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7535\u8868',
                'verbose_name_plural': '\u7535\u8868',
            },
        ),
        migrations.CreateModel(
            name='Watermeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(verbose_name='\u5ea6\u6570')),
                ('image', models.ImageField(upload_to='water', verbose_name='\u56fe\u7247')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6c34\u8868',
                'verbose_name_plural': '\u6c34\u8868',
            },
        ),
    ]
