# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wae', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammeter',
            name='image',
            field=models.ImageField(upload_to='elec/%Y/%m/%d', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='watermeter',
            name='image',
            field=models.ImageField(upload_to='water/%Y/%m/%d', verbose_name='\u56fe\u7247'),
        ),
    ]
