# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 09:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wae', '0002_auto_20180620_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='ammeter',
            name='img_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 9, 17, 12, 301000, tzinfo=utc), verbose_name='\u62cd\u6444\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='watermeter',
            name='img_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 9, 17, 12, 300000, tzinfo=utc), verbose_name='\u62cd\u6444\u65e5\u671f'),
        ),
    ]
